Repository EWHA-LUX/ONCE-BE, pull requests merged in 2024-03, with the labels that each got.

#44 [Feature] 알림 조회 API
  docker-compose.yml
  src/main/java/ewha/lux/once/domain/home/dto/AnnouncListDto.java
  src/main/java/ewha/lux/once/domain/home/dto/AnnounceListDto.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: feature, 해원

#46 [Fix] 알림 TimeZone 변경
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: 해원, fix

#47 [ Fix] Docker timezone 설정
  Dockerfile
Labels: 해원, fix

#53 [Feature] ERD 수정사항 반영
  src/main/java/ewha/lux/once/domain/card/entity/BenefitSummary.java
  src/main/java/ewha/lux/once/domain/card/entity/Card.java
  src/main/java/ewha/lux/once/domain/card/entity/EventSummary.java
Labels: feature, 해원

#55 [Fix] 커넥티드 아이디 복호화 오류 해결
  src/main/java/ewha/lux/once/global/common/ColumnEncryptor.java
Labels: 채린, fix

#61 [Feature] 카드 혜택 요약 자동화
  src/main/java/ewha/lux/once/domain/card/entity/BenefitSummary.java
  src/main/java/ewha/lux/once/domain/card/entity/Card.java
  src/main/java/ewha/lux/once/domain/card/service/CardService.java
  src/main/java/ewha/lux/once/domain/home/dto/BenefitDto.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
  src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
  src/main/java/ewha/lux/once/global/repository/BenefitSummaryRepository.java
Labels: feature, 해원

#63 [Feature & Fix] 회원 정보 조회 API 수정
  src/main/java/ewha/lux/once/domain/user/dto/UserEditResponseDto.java
  src/main/java/ewha/lux/once/domain/user/entity/Users.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
Labels: feature, 해원, fix

#65 [Feature & Fix] 회원 정보 조회 API 수정
  src/main/java/ewha/lux/once/domain/user/dto/UserEditResponseDto.java
  src/main/java/ewha/lux/once/domain/user/entity/Users.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
Labels: feature, 해원, fix

#67 [Fix] 크롤링 자동화 오류 해결 1차
  .github/workflows/gradle.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  requirements.txt
  src/main/java/ewha/lux/once/domain/card/controller/CardController.java
  src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
  src/main/resources/crawling/DatabaseInsert.py
  src/main/resources/crawling/Hana/credit.py
  src/main/resources/crawling/Hana/debit.py
  src/main/resources/crawling/Hyundai/credit.py
  src/main/resources/crawling/Hyundai/debit.py
  src/main/resources/crawling/Lotte/credit.py
  src/main/resources/crawling/Lotte/debit.py
  src/main/resources/crawling/Samsung/credit.py
  src/main/resources/crawling/Samsung/debit.py
  src/main/resources/crawling/Shinhan/credit.py
  src/main/resources/crawling/Shinhan/debit.py
Labels: 해원, fix

#68 [Fix] 크롤링 로그 출력 문제 해결
  docker-compose.yml
  src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
  src/main/resources/crawling/DatabaseInsert.py
  src/main/resources/crawling/Hana/credit.py
  src/main/resources/crawling/Hana/debit.py
  src/main/resources/crawling/Hyundai/credit.py
  src/main/resources/crawling/Hyundai/debit.py
  src/main/resources/crawling/Kookmin/credit.py
  src/main/resources/crawling/Kookmin/debit.py
  src/main/resources/crawling/Lotte/credit.py
  src/main/resources/crawling/Lotte/debit.py
  src/main/resources/crawling/Samsung/credit.py
  src/main/resources/crawling/Samsung/debit.py
  src/main/resources/crawling/Shinhan/credit.py
  src/main/resources/crawling/Shinhan/debit.py
Labels: 해원, fix
