Repository EWHA-LUX/ONCE-BE, pull requests merged in 2024-02, with the labels that each got.

#11 [Feature] 프로필 이미지 수정, 회원 탈퇴 api
  build.gradle
  src/main/java/ewha/lux/once/domain/user/controller/UserController.java
  src/main/java/ewha/lux/once/domain/user/entity/Users.java
  src/main/java/ewha/lux/once/domain/user/service/S3Uploader.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/config/S3Config.java
  src/main/resources/application.yml
Labels: feature, 채린

#17 [Fix] repository 위치 변경
  src/main/java/ewha/lux/once/domain/home/controller/HomeController.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
  src/main/java/ewha/lux/once/domain/user/controller/UserController.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/common/ResponseDto.java
  src/main/java/ewha/lux/once/global/repository/AnnouncementRepository.java
  src/main/java/ewha/lux/once/global/repository/CardCompanyRepository.java
  src/main/java/ewha/lux/once/global/repository/CardRepository.java
  src/main/java/ewha/lux/once/global/repository/ChatHistoryRepository.java
  src/main/java/ewha/lux/once/global/repository/OwnedCardRepository.java
  src/main/java/ewha/lux/once/global/repository/UsersRepository.java
  src/main/java/ewha/lux/once/global/security/JwtAuthFilter.java
  src/main/java/ewha/lux/once/global/security/JwtProvider.java
Labels: 채린, fix

#19 [Feature] 공통 응답 포맷 생성, 예외 처리 추가
  src/main/java/ewha/lux/once/domain/home/controller/HomeController.java
  src/main/java/ewha/lux/once/domain/user/controller/UserController.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/common/CommonResponse.java
  src/main/java/ewha/lux/once/global/common/CustomException.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
Labels: feature, 해원

#22 [Feat] 기능별 예외 처리 추가
  src/main/java/ewha/lux/once/domain/home/controller/HomeController.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
  src/main/java/ewha/lux/once/domain/user/controller/UserController.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
  src/main/java/ewha/lux/once/global/repository/CardCompanyRepository.java
  src/main/java/ewha/lux/once/global/repository/CardRepository.java
  src/main/java/ewha/lux/once/global/repository/UsersRepository.java
  src/main/java/ewha/lux/once/global/security/JwtProvider.java
Labels: feature, 채린

#28 [Feat] 아이디 중복 확인, 비밀번호 확인 및 변경 api 구현
  src/main/java/ewha/lux/once/domain/user/controller/UserController.java
  src/main/java/ewha/lux/once/domain/user/dto/ChangePasswordDto.java
  src/main/java/ewha/lux/once/domain/user/entity/Users.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
Labels: feature, 지민

#30 [Feat] 회원 정보 수정 api 구현
  src/main/java/ewha/lux/once/domain/user/controller/UserController.java
  src/main/java/ewha/lux/once/domain/user/dto/EditUserInfoRequestDto.java
  src/main/java/ewha/lux/once/domain/user/entity/Users.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
Labels: feature, 지민

#32 [Feature] 마이페이지 정보 조회 API 구현
  src/main/java/ewha/lux/once/domain/home/dto/AnnounceDetailDto.java
  src/main/java/ewha/lux/once/domain/home/dto/AnnounceDto.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
  src/main/java/ewha/lux/once/domain/mypage/controller/MypageController.java
  src/main/java/ewha/lux/once/domain/mypage/dto/MypageResponseDto.java
  src/main/java/ewha/lux/once/domain/mypage/service/MypageService.java
  src/main/java/ewha/lux/once/domain/user/dto/UserEditResponseDto.java
  src/main/java/ewha/lux/once/global/common/BaseEntity.java
  src/main/java/ewha/lux/once/global/repository/ChatHistoryRepository.java
  src/main/java/ewha/lux/once/global/repository/OwnedCardRepository.java
Labels: feature, 해원

#35 [Feature] 챗봇 대화 조회 API 구현
  src/main/java/ewha/lux/once/domain/mypage/controller/MypageController.java
  src/main/java/ewha/lux/once/domain/mypage/dto/ChatHistoryResponseDto.java
  src/main/java/ewha/lux/once/domain/mypage/service/MypageService.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
  src/main/java/ewha/lux/once/global/repository/ChatHistoryRepository.java
Labels: feature, 해원

#38 [Feature] 월별 혜택 조회 관련 api 구현
  src/main/java/ewha/lux/once/domain/card/controller/CardController.java
  src/main/java/ewha/lux/once/domain/card/dto/CardGoalRequestDto.java
  src/main/java/ewha/lux/once/domain/card/dto/MontlyBenefitResponseDto.java
  src/main/java/ewha/lux/once/domain/card/service/CardService.java
  src/main/java/ewha/lux/once/domain/user/entity/Users.java
Labels: feature, 지민

#39 [Feature] 카드 관리 관련 API 구현
  src/main/java/ewha/lux/once/domain/card/entity/OwnedCard.java
  src/main/java/ewha/lux/once/domain/mypage/controller/MypageController.java
  src/main/java/ewha/lux/once/domain/mypage/dto/CardListResponseDto.java
  src/main/java/ewha/lux/once/domain/mypage/service/MypageService.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
  src/main/java/ewha/lux/once/global/repository/OwnedCardRepository.java
Labels: feature, 해원
