Repository EWHA-LUX/ONCE-BE, pull requests merged in 2024-05, with the labels that each got.

#85 [Fix] 회원 탈퇴 api 수정
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
Labels: 채린, fix

#87 [Feat] 추천 카드 주카드 여부 반환
  src/main/java/ewha/lux/once/domain/home/dto/ChatDto.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: feature, 채린

#89 fix: 비밀번호 변경 오류 수정 (#88)
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
Labels: 지민, fix

#92 fix: codef 보유 카드 조회 post 변경 (#91)
  src/main/java/ewha/lux/once/domain/card/controller/CardController.java
Labels: 채린, fix

#94 [Fix] 카드 실적 입력 오류 수정
  src/main/java/ewha/lux/once/domain/card/service/CardService.java
  src/main/java/ewha/lux/once/global/repository/OwnedCardRepository.java
Labels: 지민, fix

#95 [Feature] 비콘 알림 생성
  src/main/java/ewha/lux/once/domain/home/controller/HomeController.java
  src/main/java/ewha/lux/once/domain/home/dto/AnnounceFavoriteRequestDto.java
  src/main/java/ewha/lux/once/domain/home/dto/BeaconRequestDto.java
  src/main/java/ewha/lux/once/domain/home/entity/Beacon.java
  src/main/java/ewha/lux/once/domain/home/service/AnnouncementService.java
  src/main/java/ewha/lux/once/domain/home/service/CODEFAPIService.java
  src/main/java/ewha/lux/once/domain/home/service/CODEFAsyncService.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
  src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
  src/main/java/ewha/lux/once/global/repository/BeaconRepository.java
  src/main/java/ewha/lux/once/global/repository/FavoriteRepository.java
Labels: feature, 채린

#97 [Feat] 푸시 알림 페이지 이동을 위한 알림id추가 (#72)
  src/main/java/ewha/lux/once/domain/home/dto/AnnouncementRequestDto.java
  src/main/java/ewha/lux/once/domain/home/service/AnnouncementService.java
  src/main/java/ewha/lux/once/domain/home/service/FirebaseCloudMessageService.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: feature

#99 [Fix] 단골 가게 조회 api post로 변경
  src/main/java/ewha/lux/once/domain/home/controller/HomeController.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: 채린, fix

#103 [Feat] 회원관리api에 redis추가, logout 구현
  build.gradle
  docker-compose.yml
  src/main/java/ewha/lux/once/domain/user/controller/UserController.java
  src/main/java/ewha/lux/once/domain/user/service/RedisService.java
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
  src/main/java/ewha/lux/once/global/config/JwtSecurityConfig.java
  src/main/java/ewha/lux/once/global/config/RedisConfig.java
  src/main/java/ewha/lux/once/global/config/SecurityConfig.java
  src/main/java/ewha/lux/once/global/security/JwtAuthFilter.java
  src/main/java/ewha/lux/once/global/security/JwtProvider.java
  src/main/resources/application.yml
Labels: feature, 지민, 채린

#104 [Fix] redis host 변경, Redis CLI 실행
  .github/workflows/gradle.yml
  src/main/java/ewha/lux/once/domain/user/service/UserService.java
  src/main/java/ewha/lux/once/global/security/JwtProvider.java
  src/main/resources/application.yml
Labels: 채린, fix
