Repository EWHA-LUX/ONCE-BE, pull requests merged in 2024-04, with the labels that each got.

#73 [Test] 혜택 요약 테스트 코드 추가
  src/main/java/ewha/lux/once/domain/card/controller/CardController.java
  src/main/java/ewha/lux/once/domain/card/dto/TestSummaryDto.java
  src/main/java/ewha/lux/once/domain/card/dto/TestSummaryIndexDto.java
  src/main/java/ewha/lux/once/domain/card/service/CardService.java
  src/main/java/ewha/lux/once/domain/card/service/CrawlingService.java
  src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
  src/main/java/ewha/lux/once/global/repository/CardRepository.java
Labels: 해원, test

#74 [Feature] 마이월렛 조회 닉네임 추가
  src/main/java/ewha/lux/once/domain/card/dto/MyWalletResponseDto.java
  src/main/java/ewha/lux/once/domain/card/service/CardService.java
Labels: feature, 해원

#75 [Feat] gpt 프롬프트 업데이트
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
  src/main/java/ewha/lux/once/domain/home/service/OpenaiService.java
  src/main/java/ewha/lux/once/global/common/ResponseCode.java
Labels: feature, 채린

#77 [ Feature] 홈 기본 정보 응답 추가
  src/main/java/ewha/lux/once/domain/home/dto/HomeDto.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: feature, 해원

#78 [Feature] 카드 추천 응답 수정
  src/main/java/ewha/lux/once/domain/home/dto/ChatDto.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: feature, 해원

#80 [Fix] 홈화면 검색 키워드 중복 제거
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: 채린, fix

#82 [Feat] 마이웰렛 카테고리 분류 추가
  src/main/java/ewha/lux/once/domain/card/dto/MyWalletResponseDto.java
  src/main/java/ewha/lux/once/domain/card/service/CardService.java
  src/main/java/ewha/lux/once/domain/home/service/HomeService.java
Labels: feature, 채린
